import type { Metadata } from "next";
import { CheckCircle2 } from "lucide-react";
import { ServiceCard } from "@/components/cards";
import { FinalCta } from "@/components/final-cta";
import { Reveal } from "@/components/reveal";
import { Container, PageHero, PrimaryButton, SecondaryButton, SectionHeading } from "@/components/ui";
import { processSteps, services } from "@/data/site";
export const metadata: Metadata={title:"Branding, Website, Marketing & Software Services",description:"Explore DiGi Trend services for branding, website development, social media, digital marketing, ERP software, CGI videos, automation and UI/UX.",alternates:{canonical:"/services"}};
export default function ServicesPage(){return <><PageHero eyebrow="Capabilities" title={<>Services designed to build, launch and <span className="text-red-300">grow your brand.</span></>} description="Choose a focused service or connect multiple capabilities into one clear growth plan."><PrimaryButton href="/book-demo">Get a Free Brand Audit</PrimaryButton><SecondaryButton href="/work" inverse>See Our Work</SecondaryButton></PageHero><section className="bg-white py-20 sm:py-28"><Container><SectionHeading eyebrow="What we do" title={<>Strategy, design, technology and growth — <span className="text-brand-red">under one roof.</span></>} description="Every service is structured around clear deliverables, practical execution and a professional customer experience."/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><Reveal key={s.slug} delay={(i%3)*70}><ServiceCard {...s} index={i}/></Reveal>)}</div></Container></section><section className="bg-brand-offwhite py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="How engagement works" title={<>A focused path from first discussion to <span className="text-brand-red">measurable launch.</span></>}/><div className="grid gap-4 sm:grid-cols-2">{processSteps.map((s,i)=><div key={s.title} className="rounded-[24px] bg-white p-6"><div className="flex items-center gap-4"><span className="grid size-11 place-items-center rounded-xl bg-brand-navy text-red-300"><s.icon className="size-5"/></span><div><p className="text-[10px] font-black uppercase tracking-widest text-slate-400">Step {i+1}</p><h3 className="font-heading font-black text-brand-navy">{s.title}</h3></div></div><p className="mt-4 text-sm leading-6 text-slate-600">{s.text}</p></div>)}</div></div><div className="mt-14 rounded-[30px] bg-brand-navy p-7 text-white sm:p-9"><div className="grid gap-7 md:grid-cols-3">{["Choose one service or a connected package","Receive a clear scope and execution roadmap","Launch with a professional, scalable foundation"].map(x=><div key={x} className="flex gap-3"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-red-300"/><p className="text-sm leading-6 text-white/65">{x}</p></div>)}</div></div></Container></section><FinalCta/></>}
