import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import { FinalCta } from "@/components/final-cta";
import { Reveal } from "@/components/reveal";
import { Container, PageHero, PrimaryButton, SecondaryButton, SectionHeading } from "@/components/ui";
import { caseStudies } from "@/data/site";
export const metadata:Metadata={title:"Brand, Website & Software Case Studies",description:"See how DiGi Trend solves brand, digital and operational challenges through connected strategy, design and technology.",alternates:{canonical:"/case-studies"}};
export default function CaseStudiesPage(){return <><PageHero eyebrow="Case studies" title={<>Real brands. Real challenges. <span className="text-red-300">Focused solutions.</span></>} description="See the thinking, execution and outcomes behind selected DiGi Trend projects."><PrimaryButton href="/book-demo">Discuss Your Challenge</PrimaryButton><SecondaryButton href="/work" inverse>Browse All Work</SecondaryButton></PageHero><section className="bg-white py-20 sm:py-28"><Container><SectionHeading eyebrow="Inside the work" title={<>Strategy made <span className="text-brand-red">visible.</span></>} description="Each case study shows how we connect business context with a practical creative or digital response."/><div className="mt-12 space-y-7">{caseStudies.map((c,i)=><Reveal key={c.slug}><article className="grid overflow-hidden rounded-[32px] border border-slate-200 bg-white lg:grid-cols-2"><Image src={c.image} alt={`${c.client} case study`} width={900} height={700} className={`h-full min-h-[330px] w-full object-cover ${i%2?"lg:order-2":""}`}/><div className="flex flex-col justify-center p-7 sm:p-10"><p className="text-xs font-black uppercase tracking-[.18em] text-brand-red">{c.category}</p><h2 className="font-heading mt-4 text-3xl font-black leading-[1.06] tracking-[-.05em] text-brand-navy">{c.title}</h2><p className="mt-5 text-sm leading-7 text-slate-600">{c.outcome}</p><div className="mt-6 flex flex-wrap gap-2">{c.metrics.map(m=><span key={m} className="rounded-full bg-brand-offwhite px-3 py-2 text-xs font-bold text-brand-navy">{m}</span>)}</div><Link href={`/case-studies/${c.slug}`} className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-brand-red">View full case study <ArrowUpRight className="size-4"/></Link></div></article></Reveal>)}</div></Container></section><FinalCta/></>}
