import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Check, CheckCircle2, Quote, X } from "lucide-react";
import { ArticleCard, ProjectCard, ServiceCard } from "@/components/cards";
import { Faq } from "@/components/faq";
import { FinalCta } from "@/components/final-cta";
import { HeroVisual } from "@/components/hero-visual";
import { JsonLd } from "@/components/json-ld";
import { Reveal } from "@/components/reveal";
import { Container, PrimaryButton, SecondaryButton, SectionHeading, Tag } from "@/components/ui";
import { articles, caseStudies, faqs, industries, pricing, processSteps, projects, services, siteConfig, stats, testimonials, valuePoints } from "@/data/site";

export default function HomePage() {
  return (
    <>
      <JsonLd data={{ "@context":"https://schema.org", "@type":"WebSite", name:siteConfig.name, url:siteConfig.url, description:siteConfig.description }} />
      <section className="relative overflow-hidden bg-brand-navy pb-16 pt-32 text-white sm:pt-36 lg:min-h-[820px] lg:pb-20 lg:pt-40">
        <div className="hero-grid absolute inset-0 opacity-45"/><div className="absolute -left-44 top-12 size-[500px] rounded-full bg-blue-600/20 blur-[120px]"/><div className="absolute -right-48 bottom-0 size-[520px] rounded-full bg-brand-red/20 blur-[120px]"/>
        <Container className="relative z-10 grid items-center gap-10 lg:grid-cols-[.92fr_1.08fr]">
          <Reveal><p className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-4 py-2 text-[11px] font-black uppercase tracking-[.16em] text-white/75"><span className="size-2 rounded-full bg-brand-red shadow-[0_0_14px_#ef3340]"/>360° branding & digital growth agency</p><h1 className="font-heading mt-7 text-balance text-5xl font-black leading-[.94] tracking-[-.065em] sm:text-6xl lg:text-[78px]">We don’t just design. <span className="text-red-300">We build brands that grow.</span></h1><p className="mt-7 max-w-xl text-pretty text-base leading-8 text-white/65 sm:text-lg">DiGi Trend helps businesses grow with websites, branding, social media, digital marketing, ERP software, CGI videos and complete digital strategy — all under one roof.</p><div className="mt-9 flex flex-wrap gap-3"><PrimaryButton href="/book-demo">Book Free Consultation</PrimaryButton><SecondaryButton href="/work" inverse>View Our Work</SecondaryButton></div><div className="mt-8 flex flex-wrap items-center gap-4 text-xs font-semibold text-white/55"><span className="flex -space-x-2">{["D","G","T","+"] .map((x,i)=><span key={i} className="grid size-8 place-items-center rounded-full border-2 border-brand-navy bg-white text-[10px] font-black text-brand-navy">{x}</span>)}</span><span>Trusted by growing businesses, startups and local brands.</span></div></Reveal>
          <Reveal delay={150}><HeroVisual/></Reveal>
        </Container>
      </section>

      <section className="overflow-hidden border-b border-slate-100 bg-white py-5"><div className="marquee flex w-max gap-4">{[...industries,...industries].map((name,i)=><div key={`${name}-${i}`} className="flex items-center gap-4 whitespace-nowrap px-4 text-xs font-black uppercase tracking-[.18em] text-slate-400"><span className="size-1.5 rounded-full bg-brand-red"/>{name}</div>)}</div></section>

      <section className="bg-brand-offwhite py-20 sm:py-28"><Container><div className="grid items-center gap-10 lg:grid-cols-[.88fr_1.12fr] lg:gap-16"><Reveal><SectionHeading eyebrow="The perception gap" title={<>Your business is good. <span className="text-brand-red">But does your brand look professional?</span></>} description="Good products and services can still look average when the website, logo, social media and marketing do not create one clear professional story."/><p className="mt-6 text-base leading-7 text-slate-600">At DiGi Trend, we close that gap with complete brand planning and connected digital execution.</p><div className="mt-8"><PrimaryButton href="/about">How We Think</PrimaryButton></div></Reveal><Reveal delay={120}><div className="grid gap-4 sm:grid-cols-2"><div className="rounded-[30px] border border-red-100 bg-white p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-red-50 text-brand-red"><X className="size-5"/></span><h3 className="font-heading font-black text-brand-navy">Before DiGi Trend</h3></div><ul className="mt-6 space-y-4">{["Random logo and visuals","Weak or outdated website","No brand consistency","No lead journey","Low social trust"].map(x=><li key={x} className="flex items-center gap-3 text-sm text-slate-600"><X className="size-4 text-red-400"/>{x}</li>)}</ul></div><div className="rounded-[30px] bg-brand-navy p-6 text-white shadow-[0_24px_60px_rgba(6,20,47,.16)]"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-green-400/15 text-green-300"><Check className="size-5"/></span><h3 className="font-heading font-black">After DiGi Trend</h3></div><ul className="mt-6 space-y-4">{["Premium identity","Conversion-focused website","Strong social presence","Clear marketing strategy","Connected growth system"].map(x=><li key={x} className="flex items-center gap-3 text-sm text-white/65"><Check className="size-4 text-green-300"/>{x}</li>)}</ul></div></div></Reveal></div></Container></section>

      <section className="bg-white py-20 sm:py-28"><Container><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionHeading eyebrow="Connected capabilities" title={<>Everything your brand needs. <span className="text-brand-red">One expert team.</span></>} description="Build a stronger customer journey with strategy, design, marketing and technology working together."/><Link href="/services" className="inline-flex items-center gap-2 text-sm font-extrabold text-brand-navy">View all services <ArrowRight className="size-4"/></Link></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.slice(0,8).map((s,i)=><Reveal key={s.slug} delay={(i%4)*70}><ServiceCard {...s} index={i}/></Reveal>)}</div></Container></section>

      <section className="overflow-hidden bg-brand-navy py-20 text-white sm:py-28"><Container><SectionHeading eyebrow="Our signature process" title={<>Simple, strategic and <span className="text-red-300">result-focused.</span></>} description="One clear process keeps every capability aligned with your goals." light/><div className="relative mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-6"><div className="absolute left-[8%] right-[8%] top-7 hidden h-px bg-gradient-to-r from-transparent via-white/20 to-transparent lg:block"/>{processSteps.map((step,i)=><Reveal key={step.title} delay={i*70}><div className="relative rounded-[24px] border border-white/10 bg-white/[.045] p-5 backdrop-blur-sm lg:border-0 lg:bg-transparent lg:p-0"><div className="relative z-10 grid size-14 place-items-center rounded-2xl border border-white/10 bg-[#0c1d3f] text-red-300 shadow-xl"><step.icon className="size-5"/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[.18em] text-white/35">Step {i+1}</p><h3 className="font-heading mt-2 text-lg font-black">{step.title}</h3><p className="mt-2 text-sm leading-6 text-white/50">{step.text}</p></div></Reveal>)}</div></Container></section>

      <section className="bg-white py-20 sm:py-28"><Container><SectionHeading eyebrow="Selected work" title={<>Work that looks good. <span className="text-brand-red">And works even better.</span></>} description="A selection of brand, website, social, software and CGI directions built around clear business goals."/><div className="mt-10 flex flex-wrap gap-2">{["All","Branding","Website","Social Media","CGI","UI/UX","Software"].map((x,i)=><Tag key={x}>{x}{i===0?" · 06":""}</Tag>)}</div><div className="mt-12 grid gap-x-7 gap-y-14 lg:grid-cols-2">{projects.slice(0,4).map((p,i)=><Reveal key={p.slug} delay={(i%2)*100}><ProjectCard project={p}/></Reveal>)}</div><div className="mt-12 text-center"><PrimaryButton href="/work">Explore All Work</PrimaryButton></div></Container></section>

      <section className="bg-brand-offwhite py-20 sm:py-28"><Container><div className="grid items-center gap-10 lg:grid-cols-2 lg:gap-16"><Reveal><Image src={caseStudies[0].image} alt={`${caseStudies[0].client} featured case study`} width={900} height={700} className="w-full rounded-[34px] shadow-[0_28px_70px_rgba(6,20,47,.14)]"/></Reveal><Reveal delay={120}><SectionHeading eyebrow="Featured case study" title={<>Real brands. Real strategy. <span className="text-brand-red">Real growth.</span></>} description={caseStudies[0].title}/><div className="mt-8 space-y-6">{[["Problem",caseStudies[0].problem],["Solution",caseStudies[0].solution],["Outcome",caseStudies[0].outcome]].map(([t,x])=><div key={t} className="grid grid-cols-[80px_1fr] gap-4 border-t border-slate-200 pt-5"><p className="text-xs font-black uppercase tracking-[.14em] text-brand-red">{t}</p><p className="text-sm leading-6 text-slate-600">{x}</p></div>)}</div><div className="mt-8"><PrimaryButton href={`/case-studies/${caseStudies[0].slug}`}>View Full Case Study</PrimaryButton></div></Reveal></div></Container></section>

      <section className="bg-white py-20 sm:py-28"><Container><SectionHeading eyebrow="Why DiGi Trend" title={<>Why businesses choose <span className="text-brand-red">one connected partner.</span></>} description="Because your brand grows faster when strategy, design and execution are moving in the same direction." align="center"/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{valuePoints.map((item,i)=><Reveal key={item.title} delay={(i%3)*70}><div className="h-full rounded-[28px] border border-slate-200 bg-white p-7 transition hover:-translate-y-1 hover:shadow-[0_22px_50px_rgba(6,20,47,.08)]"><item.icon className="size-7 text-brand-red"/><h3 className="font-heading mt-6 text-xl font-black tracking-[-.035em] text-brand-navy">{item.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{item.text}</p></div></Reveal>)}</div><div className="mt-14 grid grid-cols-2 gap-3 rounded-[30px] bg-brand-navy p-5 text-white sm:grid-cols-4 sm:p-7">{stats.map(s=><div key={s.value} className="rounded-2xl border border-white/10 p-5 text-center"><p className="text-3xl font-black tracking-[-.05em] text-red-300 sm:text-4xl">{s.value}</p><p className="mt-2 text-xs leading-5 text-white/50">{s.label}</p></div>)}</div></Container></section>

      <section className="overflow-hidden bg-brand-offwhite py-20 sm:py-24"><Container><SectionHeading eyebrow="Industries" title={<>Built for every business <span className="text-brand-red">that wants to grow.</span></>} align="center"/><div className="mt-10 flex flex-wrap justify-center gap-3">{industries.map(x=><div key={x} className="rounded-full border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-brand-navy shadow-sm">{x}</div>)}</div></Container></section>

      <section className="bg-white py-20 sm:py-28"><Container><SectionHeading eyebrow="Starting packages" title={<>Start small. <span className="text-brand-red">Grow smart.</span></>} description="Choose a focused starting point or combine capabilities into a custom growth plan." align="center"/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{pricing.map((p,i)=><Reveal key={p.name} delay={i*60}><div className={`relative h-full rounded-[28px] border p-6 ${p.featured?"border-brand-red bg-brand-navy text-white shadow-[0_24px_65px_rgba(6,20,47,.18)]":"border-slate-200 bg-white"}`}>{p.featured&&<span className="absolute right-5 top-5 rounded-full bg-brand-red px-3 py-1 text-[9px] font-black uppercase tracking-wider text-white">Popular</span>}<p className={`text-[10px] font-black uppercase tracking-[.15em] ${p.featured?"text-red-300":"text-brand-red"}`}>{p.eyebrow}</p><h3 className="font-heading mt-4 text-xl font-black">{p.name}</h3><p className={`mt-2 text-2xl font-black ${p.featured?"text-white":"text-brand-navy"}`}>{p.price}</p><p className={`mt-4 text-sm leading-6 ${p.featured?"text-white/55":"text-slate-600"}`}>{p.description}</p><ul className="mt-6 space-y-3">{p.features.map(x=><li key={x} className={`flex gap-2 text-sm ${p.featured?"text-white/70":"text-slate-600"}`}><CheckCircle2 className={`mt-0.5 size-4 shrink-0 ${p.featured?"text-red-300":"text-brand-red"}`}/>{x}</li>)}</ul><Link href="/book-demo" className={`mt-7 block rounded-full px-4 py-3 text-center text-sm font-extrabold ${p.featured?"bg-brand-red text-white":"bg-slate-100 text-brand-navy"}`}>{p.cta}</Link></div></Reveal>)}</div></Container></section>

      <section className="bg-brand-offwhite py-20 sm:py-28"><Container><SectionHeading eyebrow="Client perspective" title={<>What clients say about <span className="text-brand-red">working with us.</span></>} align="center"/><div className="mt-12 grid gap-5 lg:grid-cols-3">{testimonials.map((t,i)=><Reveal key={t.name} delay={i*80}><figure className="h-full rounded-[28px] bg-white p-7 shadow-[0_16px_45px_rgba(6,20,47,.06)]"><Quote className="size-8 fill-red-50 text-brand-red"/><blockquote className="mt-6 text-base font-semibold leading-7 text-brand-navy">“{t.quote}”</blockquote><figcaption className="mt-7 border-t border-slate-100 pt-5"><p className="font-black text-brand-navy">{t.name}</p><p className="mt-1 text-xs text-slate-500">{t.business} · {t.service}</p></figcaption></figure></Reveal>)}</div></Container></section>

      <section className="bg-white py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr] lg:gap-16"><SectionHeading eyebrow="FAQ" title={<>Questions before <span className="text-brand-red">starting?</span></>} description="Clear answers about our capabilities, pricing and process."/><Faq items={faqs}/></div></Container></section>

      <section className="bg-brand-offwhite py-20 sm:py-28"><Container><div className="flex flex-col justify-between gap-8 lg:flex-row lg:items-end"><SectionHeading eyebrow="Insights" title={<>Ideas for building a <span className="text-brand-red">stronger business brand.</span></>} description="Practical thinking on branding, websites, marketing, technology and business growth."/><Link href="/insights" className="inline-flex items-center gap-2 text-sm font-extrabold text-brand-navy">View all insights <ArrowRight className="size-4"/></Link></div><div className="mt-12 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{articles.slice(0,3).map((a,i)=><Reveal key={a.slug} delay={i*80}><ArticleCard article={a}/></Reveal>)}</div></Container></section>
      <FinalCta/>
    </>
  );
}
