import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import type { LucideIcon } from "lucide-react";

export function ServiceCard({ slug, title, summary, icon: Icon, index }: { slug: string; title: string; summary: string; icon: LucideIcon; index: number }) {
  return <Link href={`/services/${slug}`} className="group relative overflow-hidden rounded-[28px] border border-slate-200 bg-white p-6 transition duration-300 hover:-translate-y-1 hover:border-red-100 hover:shadow-[0_24px_60px_rgba(6,20,47,.1)] sm:p-7"><span className="absolute right-5 top-4 text-5xl font-black tracking-[-.08em] text-slate-50 transition group-hover:text-red-50">0{index+1}</span><div className="relative grid size-12 place-items-center rounded-2xl bg-slate-100 text-brand-navy transition group-hover:bg-brand-red group-hover:text-white"><Icon className="size-5"/></div><h3 className="font-heading relative mt-8 text-xl font-black tracking-[-.035em] text-brand-navy">{title}</h3><p className="relative mt-3 text-sm leading-6 text-slate-600">{summary}</p><span className="relative mt-7 inline-flex items-center gap-2 text-sm font-extrabold text-brand-red">Explore Service <ArrowUpRight className="size-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></span></Link>;
}

export function ProjectCard({ project }: { project: { slug: string; client: string; category: string; result: string; image: string; services: string } }) {
  return <article className="group"><Link href={`/case-studies/${project.slug}`} className="block overflow-hidden rounded-[30px] bg-slate-100"><Image src={project.image} alt={`${project.client} ${project.category} project`} width={800} height={600} className="aspect-[4/3] h-auto w-full object-cover transition duration-700 group-hover:scale-[1.035]"/></Link><div className="mt-5 flex items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.16em] text-brand-red">{project.services}</p><h3 className="font-heading mt-2 text-2xl font-black tracking-[-.04em] text-brand-navy">{project.client}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-slate-600">{project.result}</p></div><Link href={`/case-studies/${project.slug}`} className="grid size-11 shrink-0 place-items-center rounded-full border border-slate-200 bg-white text-brand-navy transition group-hover:border-brand-red group-hover:bg-brand-red group-hover:text-white" aria-label={`View ${project.client} case study`}><ArrowUpRight className="size-5"/></Link></div></article>;
}

export function ArticleCard({ article }: { article: { slug: string; title: string; category: string; excerpt: string; date: string; read: string; image: string } }) {
  return <article className="group overflow-hidden rounded-[28px] border border-slate-200 bg-white transition hover:-translate-y-1 hover:shadow-[0_24px_55px_rgba(6,20,47,.1)]"><Link href={`/insights/${article.slug}`}><Image src={article.image} alt={article.title} width={800} height={500} className="aspect-[8/5] w-full object-cover transition duration-700 group-hover:scale-[1.03]"/></Link><div className="p-6"><div className="flex items-center gap-3 text-[11px] font-bold uppercase tracking-[.12em] text-slate-400"><span className="text-brand-red">{article.category}</span><span>•</span><span>{article.read}</span></div><h3 className="font-heading mt-4 text-xl font-black leading-tight tracking-[-.035em] text-brand-navy"><Link href={`/insights/${article.slug}`}>{article.title}</Link></h3><p className="mt-3 text-sm leading-6 text-slate-600">{article.excerpt}</p><p className="mt-5 text-xs font-semibold text-slate-400">{article.date}</p></div></article>;
}
