import { ArrowUpRight, BarChart3, CheckCircle2, Camera, MousePointer2, Sparkles } from "lucide-react";

export function HeroVisual() {
  return (
    <div className="relative mx-auto min-h-[500px] max-w-[590px] lg:min-h-[610px]">
      <div className="absolute inset-x-3 top-10 rotate-[2deg] rounded-[32px] border border-white/10 bg-white/5 p-3 shadow-2xl backdrop-blur-sm sm:inset-x-8">
        <div className="overflow-hidden rounded-[25px] bg-white shadow-[0_30px_90px_rgba(0,0,0,.3)]">
          <div className="flex h-10 items-center gap-2 border-b border-slate-100 px-4"><span className="size-2.5 rounded-full bg-red-400"/><span className="size-2.5 rounded-full bg-amber-300"/><span className="size-2.5 rounded-full bg-green-400"/><span className="ml-3 h-4 flex-1 rounded-full bg-slate-100"/></div>
          <div className="grid min-h-[320px] grid-cols-[1.2fr_.8fr] gap-5 p-6 sm:min-h-[390px] sm:p-8">
            <div><span className="inline-flex rounded-full bg-red-50 px-3 py-1 text-[10px] font-black uppercase tracking-wider text-brand-red">Brand growth system</span><h3 className="font-heading mt-5 max-w-xs text-3xl font-black leading-[.98] tracking-[-.06em] text-brand-navy sm:text-5xl">Make your business impossible to ignore.</h3><div className="mt-6 flex gap-2"><span className="rounded-full bg-brand-red px-4 py-2 text-[10px] font-bold text-white">Start a project</span><span className="rounded-full border border-slate-200 px-4 py-2 text-[10px] font-bold text-brand-navy">View work</span></div></div>
            <div className="relative overflow-hidden rounded-3xl bg-brand-navy p-5 text-white"><div className="absolute -right-10 -top-10 size-36 rounded-full bg-brand-red/40 blur-2xl"/><Sparkles className="relative size-7 text-red-300"/><p className="relative mt-16 text-xs text-white/50">Growth index</p><p className="relative mt-1 text-4xl font-black">+148%</p><svg viewBox="0 0 220 90" className="relative mt-4 w-full"><path d="M2 76 C35 70 42 58 70 60 C105 62 112 30 143 38 C175 46 177 10 218 8" fill="none" stroke="#ef3340" strokeWidth="5" strokeLinecap="round"/><path d="M2 76 C35 70 42 58 70 60 C105 62 112 30 143 38 C175 46 177 10 218 8 L218 90 L2 90Z" fill="url(#g)" opacity=".25"/><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop stopColor="#ef3340"/><stop offset="1" stopColor="#ef3340" stopOpacity="0"/></linearGradient></defs></svg></div>
          </div>
        </div>
      </div>
      <div className="absolute -left-2 bottom-10 w-[190px] -rotate-3 rounded-[25px] border border-white/20 bg-white p-4 text-brand-navy shadow-[0_25px_70px_rgba(0,0,0,.25)] sm:left-0 sm:w-[220px]"><div className="flex items-center justify-between"><div className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-fuchsia-500 to-orange-400 text-white"><Camera className="size-4"/></div><span className="text-[9px] font-black uppercase tracking-widest text-slate-400">Social</span></div><div className="mt-4 aspect-[4/3] rounded-2xl bg-[linear-gradient(135deg,#06142f,#ef3340)] p-4 text-white"><p className="text-xs font-bold text-white/60">Your next</p><p className="mt-1 text-2xl font-black leading-none">big brand move.</p><ArrowUpRight className="ml-auto mt-8"/></div></div>
      <div className="absolute -right-1 bottom-2 w-[205px] rotate-3 rounded-[25px] border border-white/15 bg-[#0b1b3b] p-5 text-white shadow-[0_25px_70px_rgba(0,0,0,.28)] sm:right-2 sm:w-[240px]"><div className="flex items-center justify-between"><BarChart3 className="text-red-300"/><span className="text-[9px] font-bold text-white/40">LIVE DASHBOARD</span></div><p className="mt-6 text-xs text-white/45">Qualified inquiries</p><div className="mt-1 flex items-end justify-between"><p className="text-4xl font-black">286</p><span className="rounded-full bg-green-400/15 px-2 py-1 text-[10px] font-bold text-green-300">↑ 32%</span></div><div className="mt-5 grid grid-cols-7 items-end gap-1.5">{[35,55,42,72,60,88,100].map((h,i)=><span key={i} className="rounded-t bg-gradient-to-t from-brand-red to-red-300" style={{height:h*0.65}}/>)}</div></div>
      <div className="absolute right-5 top-2 flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold text-white backdrop-blur"><CheckCircle2 className="size-4 text-green-300"/>One team. One strategy.</div>
      <MousePointer2 className="absolute left-[45%] top-[48%] size-8 -rotate-12 fill-white text-brand-navy drop-shadow-lg"/>
    </div>
  );
}
