import type { Metadata } from "next";
import Image from "next/image";
import { notFound } from "next/navigation";
import { CheckCircle2 } from "lucide-react";
import { FinalCta } from "@/components/final-cta";
import { JsonLd } from "@/components/json-ld";
import { Container, PageHero, PrimaryButton, SecondaryButton, SectionHeading } from "@/components/ui";
import { caseStudies, siteConfig } from "@/data/site";
export function generateStaticParams(){return caseStudies.map(x=>({slug:x.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const c=caseStudies.find(x=>x.slug===slug);return c?{title:`${c.client} Case Study`,description:c.title,alternates:{canonical:`/case-studies/${slug}`}}:{}}
export default async function CaseStudy({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const c=caseStudies.find(x=>x.slug===slug);if(!c)notFound();return <><JsonLd data={{"@context":"https://schema.org","@type":"CreativeWork",name:c.title,about:c.client,creator:{"@type":"Organization",name:siteConfig.name},url:`${siteConfig.url}/case-studies/${c.slug}`}}/><PageHero eyebrow={c.category} title={<>{c.title}</>} description={`A DiGi Trend case study for ${c.client}.`}><PrimaryButton href="/book-demo">Start a Similar Project</PrimaryButton><SecondaryButton href="/case-studies" inverse>All Case Studies</SecondaryButton></PageHero><section className="bg-white py-14 sm:py-20"><Container><Image src={c.image} alt={`${c.client} project presentation`} width={1400} height={900} priority className="w-full rounded-[36px] shadow-[0_30px_80px_rgba(6,20,47,.14)]"/><div className="mt-14 grid gap-10 lg:grid-cols-3">{[["The problem",c.problem],["Our solution",c.solution],["The outcome",c.outcome]].map(([t,x],i)=><div key={t} className="border-t-2 border-brand-red pt-6"><p className="text-[10px] font-black uppercase tracking-[.18em] text-slate-400">0{i+1}</p><h2 className="font-heading mt-3 text-2xl font-black text-brand-navy">{t}</h2><p className="mt-4 text-sm leading-7 text-slate-600">{x}</p></div>)}</div></Container></section><section className="bg-brand-offwhite py-20"><Container><SectionHeading eyebrow="Project impact" title={<>A stronger system for <span className="text-brand-red">the next stage of growth.</span></>} align="center"/><div className="mx-auto mt-10 grid max-w-4xl gap-4 sm:grid-cols-3">{c.metrics.map(x=><div key={x} className="flex items-center gap-3 rounded-2xl bg-white p-5 text-sm font-bold text-brand-navy"><CheckCircle2 className="size-5 text-brand-red"/>{x}</div>)}</div></Container></section><FinalCta/></>}
