import type { Metadata } from "next";
import Link from "next/link";
import { CheckCircle2 } from "lucide-react";
import { Faq } from "@/components/faq";
import { FinalCta } from "@/components/final-cta";
import { Container, PageHero, PrimaryButton, SecondaryButton, SectionHeading } from "@/components/ui";
import { pricing } from "@/data/site";
export const metadata:Metadata={title:"Branding, Website & Growth Packages",description:"Explore starting packages for branding, websites, social media and connected digital growth from DiGi Trend.",alternates:{canonical:"/pricing"}};
const faq=[{q:"Are these fixed final prices?",a:"The Website Starter price is a defined starting point. Other packages are quoted after understanding scope, deliverables and timelines."},{q:"Can I combine services?",a:"Yes. We can combine branding, website, social, marketing, CGI and automation into one phased growth plan."},{q:"Do you offer monthly support?",a:"Yes. Ongoing support can include content, campaigns, website improvement, design and digital growth consulting."},{q:"What happens after consultation?",a:"You receive a recommended scope, delivery stages, timeline and commercial proposal before work begins."}];
export default function PricingPage(){return <><PageHero eyebrow="Pricing & packages" title={<>Start small. Grow smart. <span className="text-red-300">Scale with clarity.</span></>} description="Practical starting packages for businesses that want professional output without unnecessary complexity."><PrimaryButton href="/book-demo">Get a Custom Plan</PrimaryButton><SecondaryButton href="/services" inverse>Compare Services</SecondaryButton></PageHero><section className="bg-white py-20 sm:py-28"><Container><SectionHeading eyebrow="Starting points" title={<>Choose the right first move for <span className="text-brand-red">your business.</span></>} description="Every package can be adapted after a discovery conversation." align="center"/><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{pricing.map(p=><div key={p.name} className={`relative rounded-[28px] border p-7 ${p.featured?"border-brand-red bg-brand-navy text-white shadow-xl":"border-slate-200 bg-white"}`}><p className={`text-[10px] font-black uppercase tracking-[.16em] ${p.featured?"text-red-300":"text-brand-red"}`}>{p.eyebrow}</p><h2 className="font-heading mt-4 text-2xl font-black">{p.name}</h2><p className="mt-3 text-xl font-black">{p.price}</p><p className={`mt-4 text-sm leading-6 ${p.featured?"text-white/55":"text-slate-600"}`}>{p.description}</p><ul className="mt-6 space-y-3">{p.features.map(x=><li key={x} className={`flex gap-2 text-sm ${p.featured?"text-white/70":"text-slate-600"}`}><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-brand-red"/>{x}</li>)}</ul><Link href="/book-demo" className={`mt-7 block rounded-full px-4 py-3 text-center text-sm font-extrabold ${p.featured?"bg-brand-red text-white":"bg-slate-100 text-brand-navy"}`}>{p.cta}</Link></div>)}</div><p className="mt-8 text-center text-xs leading-6 text-slate-400">Prices exclude applicable taxes and third-party costs such as hosting, ad spend, premium licenses or production expenses unless specified.</p></Container></section><section className="bg-brand-offwhite py-20 sm:py-28"><Container><div className="grid gap-10 lg:grid-cols-[.7fr_1.3fr]"><SectionHeading eyebrow="Pricing FAQ" title={<>Clear answers before you <span className="text-brand-red">choose a plan.</span></>}/><Faq items={faq}/></div></Container></section><FinalCta/></>}
